chore: edit compendium text
terjesyl/sikt-workshop pull request #1
Opened 2024-05-10 12:33 UTC by pooriamehregan

Synes kompendiet ser veldig bra ut! 💯
Dette her er forslag på hva som kan endres etter min mening.

2024-05-13 11:25 UTC, terjesyl commented on example-template.ttl
> +    adms:versionNotes ... .
`\n`

2024-05-13 11:31 UTC, terjesyl commented on ressurshefte/ressurshefte.md
> +AdaLovelace har interesse Programmering
Foreslår å beholde ettords-egenskapene ("type", "navn", "interesse", "kjenner" , osv.) for å tydeliggjøre hva som er subjekt, predikat og objekt i denne uformelle syntaksen.

2024-05-13 11:33 UTC, terjesyl commented on ressurshefte/ressurshefte.md
> +Hint: sjekk DCAT-AP-NO-spesifikasjonen for hvilke felt som er obligatoriske for en datasettbeskrivelse.
Vil helst unngå at de må gå til DCAT-AP-NO i første oppgave siden det kan bli litt overveldende, men kan tydeliggjøre hva som er de obligatoriske feltene.

2024-05-13 11:33 UTC, terjesyl commented on ressurshefte/ressurshefte.md
> +## OPPGAVER - vanskelighetsgrad: Lett
Foreslår å beholde opprinnelig tittel:)

2024-05-15 08:10 UTC, pooriamehregan commented
Da slettet jeg forslagene og gjorde en ny commit

2024-05-15 10:25 UTC, terjesyl approved these changes

2024-05-15 14:28 UTC, terjesyl commented on example-template.ttl
> +@prefix ns2: <http://xmlns.com/foaf/0.1/> .
Disse to kan fjernes:)

2024-05-15 14:33 UTC, terjesyl requested changes

2024-05-15 14:33 UTC, terjesyl commented on example-template.ttl
> +
og så trenger du et par prefikser til:

```turtle
@prefix adms: <http://www.w3.org/ns/adms#> .
@prefix prov: <http://www.w3.org/ns/prov#> .
@prefix cpsv: <http://purl.org/vocab/cpsv#> .
@prefix dqv: <http://www.w3.org/ns/dqv#> .
@prefix owl: <http://www.w3.org/2002/07/owl#> .
```

2024-05-23 10:52 UTC, terjesyl approved these changes

2024-05-23 12:11 UTC, merged